### PR TITLE
feat: upgrade to Cats Effect 3

### PR DESCRIPTION
**Pull request by Kazark**
Depends on #277.

- [x] Get compiling
- [x] Review joining strategy for `AutoFetchingCache` with @ChristopherDavenport .
- [x] Get tests green; looked for help [here](https://stackoverflow.com/q/67591539/834176).

### CODE REVIEW

**Comment by Ali-Mahmood** [comment]
Any update on this?

**Comment by Kazark** [comment]
I forgot this was still held up on my stuff not working. Not sure when I'm going to get back to it.

**Comment by Kazark** [comment]
Did not mean to close.

**Comment by Kazark** [comment]
@ChristopherDavenport let me know if you want me to submit a WIP PR for as far as I got trying to get these testing working with virtual time on CE3. I did make some progress on it, but never got past them failing.

Anything else you'd like to see in order to get this merged? Sorry that I forgot about it for so long.

**Pull request merged**
